### ISSUE TITLE
Justified Text

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#10]
Make All Articles and text/content justified.

![screen shot 2017-04-02 at 4 50 33 pm](https://cloud.githubusercontent.com/assets/26785931/24585753/91d18980-17c4-11e7-8ab6-67c306c70794.png)

**Comment by intersperse** [comment]
Sir text are not yet justified.

**Comment by bsilverio** [comment]
![-_1616x876_ 1600x768 _-_2017-04-03_15 03 15](https://cloud.githubusercontent.com/assets/1501806/24598585/b662c61e-187e-11e7-99e6-3db05d553246.png)
Please force refresh, already is.
