### ISSUE TITLE
OEM Approvals for Products

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#16]
The OEM approvals that we have are only for X9 Products. 
Please make sure we have the OEM approvals for all the products under product information.

**Comment by intersperse** [comment]
1. Change Global Partners to OEM Approvals in the About Us.
2. Remove Peugeot and MTU in EOM Approvals
3. Align properly the write-up and name of Chairman

**Comment by bsilverio** [comment]
3. Align properly the write-up and name of Chairman
** Like how?  The design is that the writeup is centered vertically,

**Comment by bsilverio** [comment]
MTU and Peugeot removed
