### ISSUE TITLE
Product Data Sheet

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#18]
Is the violet color because when it is downloaded?
Is it from the soft file we gave to you Sir?

![violet](https://cloud.githubusercontent.com/assets/26785931/24601414/5f141e78-188b-11e7-84c4-04a5cc346b83.jpg)

**Comment by intersperse** [comment]
Like the picture below it has OEM approvals/numbers (see photo)
But it does not show when I click SEE MORE>>

![screen shot 2017-04-03 at 4 36 20 pm](https://cloud.githubusercontent.com/assets/26785931/24601489/b0439314-188b-11e7-9ce0-0e3d7e851942.png)

**Comment by intersperse** [comment]
RE: change of colors

Is it because we don't force refresh all the time? 

![2](https://cloud.githubusercontent.com/assets/26785931/24601557/e4e16812-188b-11e7-9463-11d98f1f5ac5.jpg)
![3](https://cloud.githubusercontent.com/assets/26785931/24601558/e529a366-188b-11e7-9e15-f7334aa44dc9.jpg)

**Comment by bsilverio** [comment]
Its caused by many factors. Browser, pdf viewer, internet speed. But this part is out of our control. Im not doing anything special about it. Just displaying it. So there's nothing i can change to improve this
