### ISSUE TITLE
Remove content in Satellite Offices

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#2]
There shall be no other details below Satellite Offices.

**Comment by intersperse** [comment]
Make Satellite off muna but existing.

**Comment by bsilverio** [comment]
Fixed. No more contents

**Comment by intersperse** [comment]
Off "Satellite Offices" too.

**Comment by bsilverio** [comment]
What do you mean off?

**Comment by bsilverio** [comment]
I've already removed the title
