### ISSUE TITLE
Careers

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#20]
1. In Careers put a direct link to email

**Comment by bsilverio** [comment]
Like how?  May I have a sample screenshot?

**Comment by intersperse** [comment]
![screen shot 2017-04-07 at 11 44 04 am](https://cloud.githubusercontent.com/assets/26785931/24784793/8ad49be2-1b87-11e7-968b-61726ce3ea34.png)

**Comment by bsilverio** [comment]
Fixed
