### ISSUE TITLE
Landing Page Font Size

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#21]
1. In Landing Page increase size of font of S.M.A.R.T description

**Comment by bsilverio** [comment]
Fixed

**Comment by intersperse** [comment]
Please fix shadows below.

![screen shot 2017-04-07 at 11 37 42 am](https://cloud.githubusercontent.com/assets/26785931/24784652/a87ef5bc-1b86-11e7-8197-5c439f9b52df.png)

**Comment by intersperse** [comment]
Visual overlaps text

![screen shot 2017-04-07 at 11 28 08 am](https://cloud.githubusercontent.com/assets/26785931/24784667/b77ebfd4-1b86-11e7-81b6-fa3b33d04e78.png)

**Comment by intersperse** [comment]
layout of the landing Page

![landing page](https://cloud.githubusercontent.com/assets/26785931/24784684/d906bad0-1b86-11e7-80b9-6f6718eaa2ef.jpg)

**Comment by bsilverio** [comment]
Please separate entries of different issues.
