### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#22]
Update Facebook icon

**Comment by bsilverio** [comment]
Facebook is already blue as discussed

**Comment by intersperse** [comment]
Here's updated logo of FB

![screen shot 2017-04-07 at 11 40 06 am](https://cloud.githubusercontent.com/assets/26785931/24784709/f8a4b482-1b86-11e7-9bb8-6914c2207818.png)

**Comment by bsilverio** [comment]
That's a screenshot from facebook page.  No high res image?

**Comment by bsilverio** [comment]
NVM, copied facebook's icon.  Already fixed.
