### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#23]
Please align name proportionate to the visual. Attached is the updated message from the chairman. 

![screen shot 2017-04-07 at 11 49 43 am](https://cloud.githubusercontent.com/assets/26785931/24784926/79860eec-1b88-11e7-8d9b-50dd1a575d64.png)

**Comment by intersperse** [comment]
A Nation Evolving
I would like to thank SK Lubricants and my global partners for believing in my vision. Your continued support will undoubtedly make that vital difference in catapulting this country to the global stage of economic progress and a commitment to a greener imprint for the future.

As we step into the new world and as we celebrate the 20th anniversary of SK’s ZIC brand in the global market, it is evident that there should be a potent universal desire from every leader of every country and organization to help promote an eco-friendly sustainable oil and lubricant solution. This commitment and your support I hope will address the growing concerns of our environment and all our nations evolving. In behalf of SK Lubricants, we thank you for your share in this vital quest.
Timmy G. Tan
Chairman of SK Techno-Lube Corporation

**Comment by bsilverio** [comment]
fixed
