### ISSUE TITLE
On Mobile

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#24]
The Distributor and Dealer aren't clickable on mobile.

**Comment by intersperse** [comment]
It should be downloadable.

**Comment by bsilverio** [comment]
What is downloadable? Yes itnis clickable

**Comment by bsilverio** [comment]
Ok. Found it. The button are, but not the regions

**Comment by bsilverio** [comment]
But what is downloadable?

**Comment by intersperse** [comment]
Downloadable po ang MSDS at PDS. When they clicked it.

**Comment by bsilverio** [comment]
The design was it should be viewable, it's same sa download, after viewing users can save it.
