### ISSUE TITLE
PDS & MSDS

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#25]
Please shorten the dropdown box (white) enough/ exactly fitted on the text. Box is too long with no words.
![screen shot 2017-04-15 at 12 57 15 pm](https://cloud.githubusercontent.com/assets/26785931/25060899/345aa9dc-21db-11e7-8067-8e14a174054b.png)

**Comment by bsilverio** [comment]
Issue not related to title

**Comment by bsilverio** [comment]
done
