### ISSUE TITLE
MSDS Content

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#26]
The content for MSDS for X9 5w-40 is wrong. I tried uploading the right MSDS PDF file. It doesn't adopt on demo even if I force refresh. Same goes with other products' MSDS. When I change them they don't adopt.

Photo attached is wrong MSDS of X9 5w-40.

![screen shot 2017-04-15 at 1 08 18 pm](https://cloud.githubusercontent.com/assets/26785931/25060953/9eae1bc4-21dc-11e7-8315-5f7f2947d7ea.png)

**Comment by intersperse** [comment]
Same goes with SK-ZIC X3 15W-40
It doesn't adopt

**Comment by intersperse** [comment]
Same goes with SK-ZIC X9000 15W-40
It doesn't adopt too

It seems like it's a default MSDS shown is ZIC TOP 5w-30

**Comment by intersperse** [comment]
I double checked I reload the link itself it worked.

**Comment by bsilverio** [comment]
Is this fixed?
