### ISSUE TITLE
MSDS Oops something went wrong

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#27]
![screen shot 2017-04-15 at 2 30 12 pm](https://cloud.githubusercontent.com/assets/26785931/25061407/21faf92e-21e8-11e7-90bf-97cee735ed7c.png)

Content for this product
 http://demo.zicph.com/product/msds/36/SK-ZIC_X5_Diesel_15W-40.pdf

**Comment by bsilverio** [comment]
This works on mine
