### ISSUE TITLE
BETA

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#29]
Please put on top near tagline on the landing page the word "BETA".

**Comment by intersperse** [comment]
Also what's the button or menu tab to click when I want to go back to the landing page the one with SMART?

**Comment by bsilverio** [comment]
Logo

**Comment by bsilverio** [comment]
What tagline?

**Comment by bsilverio** [comment]
Which one is the tagline?

**Comment by intersperse** [comment]
Here Sir.

![screen shot 2017-04-16 at 11 34 03 am](https://cloud.githubusercontent.com/assets/26785931/25068507/ae6ee658-2298-11e7-80d6-0a6e6e9b0bb3.png)

**Comment by bsilverio** [comment]
Image yan, we can't just add a beta word in that.. If you want, send me an image with the beta word on it
