### ISSUE TITLE
BETA WEBSITE

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#30]
Please make the website beta link:

www.zicph.com

Include the "BETA" word.

Thank you.

**Comment by bsilverio** [comment]
Include the beta word?

**Comment by intersperse** [comment]
Yes Sir parang nakalagay lang na beta po sabi ni Sir Paul.

**Comment by intersperse** [comment]
Sir working palang po ang link right?

**Comment by bsilverio** [comment]
Saan
