### ISSUE TITLE
Put a scroll bar in the Dealer Locator

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#5]
Put a scroll bar same as the Distributor.

![screen shot 2017-04-02 at 4 13 39 pm](https://cloud.githubusercontent.com/assets/26785931/24585539/88928e46-17bf-11e7-9c8d-8019876b92eb.png)

**Comment by intersperse** [comment]
No scroll bar yet.

**Comment by intersperse** [comment]
![screen shot 2017-04-03 at 3 10 52 pm](https://cloud.githubusercontent.com/assets/26785931/24598761/bf278d38-187f-11e7-998f-389fa7ceb2cb.png)

**Comment by bsilverio** [comment]
Fixed
