### ISSUE TITLE
Make Tabs on-hover

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#6]
Make Tabs setting on-hover same as the Landing Page S.M.A.R.T

![screen shot 2017-04-02 at 4 15 34 pm](https://cloud.githubusercontent.com/assets/26785931/24585543/adfaef7a-17bf-11e7-8eeb-a4d2e2914d28.png)

**Comment by intersperse** [comment]
Sir how about this?

**Comment by bsilverio** [comment]
This is not part of the original discussed design. This came in too late on the devt phase. It will break the layout
