### ISSUE TITLE
Tabs Details on-click

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#7]
Tabs details on-click different from the tabs which is on-hover.

Make sure the BOTTLES, PRODUCT INFORMATION, AND RELATED PRODUCTS  complement the clicked option.
Moreover, the arrow of the related products seems to be misplaced and little bottles even when force refreshed don't show.

![screen shot 2017-04-02 at 4 18 39 pm](https://cloud.githubusercontent.com/assets/26785931/24585566/9b08fa32-17c0-11e7-9664-ecde43f504e0.png)

**Comment by bsilverio** [comment]
Fixed
