### ISSUE TITLE
Product Information

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#8]
Please make sure when a customer clicks a certain product the product description should already be visible not the OEM Approval.

There has been changes they want the information to be prioritized.

Moreover, please make sure the ACEA or the Product Name does not jump below. Based on the photo the "40" is placed below. The client is very much particular with indention. Please make sure text goes continuously. 

>> Show More >> should be placed below Product Information above Product Data Sheet. Also, when Show More is clicked that's the only time it should show the OEM Approvals and Numbers. 

![screen shot 2017-04-02 at 4 25 48 pm](https://cloud.githubusercontent.com/assets/26785931/24585592/851abc82-17c1-11e7-8f5a-9322e0899463.png)

**Comment by intersperse** [comment]
OEM approval number is out of the box

![screen shot 2017-04-03 at 3 07 41 pm](https://cloud.githubusercontent.com/assets/26785931/24598694/564661c2-187f-11e7-8760-8a2d176f0acd.png)

**Comment by bsilverio** [comment]
Fixed
