### ISSUE TITLE
Add Industrial Tab in Products

### ISSUE THREAD

**Issue by intersperse** [intersperse/zicph#9]
Order of tabs is PCDO/HDDO, MCO, Gear Oil, ATF, Auxiliary Oil, Grease, Industrial

![screen shot 2017-04-02 at 4 15 34 pm](https://cloud.githubusercontent.com/assets/26785931/24585733/55af5f36-17c4-11e7-925b-c79e5d1d0f88.png)

**Comment by intersperse** [comment]
PCMO, PCDO/HDDO, MCO, Gear Oil, ATF, Auxiliary , Grease, Industrial are the names and order.

Please remove Automotive in Gear Oil and Oil in Auxiliary. (Also the spelling)

**Comment by bsilverio** [comment]
Fixed
